package com.dth.util;

import java.util.List;

public interface SentenceProcessor<S, W> {

    /**
     * Processes the sentence in order to create words from it. The resultant
     * words will be stored in an internal collection, which can be accessed
     * from {@code getWords()} method.
     *
     * NOTE: Because the results often need to be preprocessed before they can
     * be accessed, it's advised to use an utility class that does this task, a
     * {@code WordProcessor} for example.
     *
     * @param sentence
     */
    public void processSentence(S sentence);

    /**
     * Returns the list of words generated by the {@code #processFile()} method.
     * If the {@code #processFile()} hasn't been run before accessing the words,
     * or there was a problem with the text file, the list will be empty.
     *
     * @return the list of words.
     */
    public List<W> getWords();
}
